# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: build

on: [push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.x'
    - name: Install Platform IO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
    - name: Install all modules
      run: ./install.sh
    - name: Build production application
      run: ./build-production.sh
    - name: Run e2e test for the whole application
      run: ./e2e.sh